#ifndef COLORS_H
#define COLORS_H

#include <stdint.h>

// Basic colors
#define COLOR_BLACK       0xFF000000
#define COLOR_WHITE       0xFFFFFFFF
#define COLOR_RED         0xFFFF0000
#define COLOR_GREEN       0xFF00FF00
#define COLOR_BLUE        0xFF0000FF
#define COLOR_YELLOW      0xFFFFFF00
#define COLOR_CYAN        0xFF00FFFF
#define COLOR_MAGENTA     0xFFFF00FF
#define COLOR_GRAY        0xFF808080
#define COLOR_LIGHT_GRAY  0xFFC0C0C0
#define COLOR_DARK_GRAY   0xFF404040

// Extended Colors
#define COLOR_ORANGE      0xFFFFA500
#define COLOR_PINK        0xFFFFC0CB
#define COLOR_PURPLE      0xFF800080
#define COLOR_BROWN       0xFFA52A2A
#define COLOR_LIGHT_BLUE  0xFFADD8E6
#define COLOR_LIGHT_GREEN 0xFF90EE90
#define COLOR_GOLD        0xFFFFD700
#define COLOR_SILVER      0xFFC0C0C0
#define COLOR_TEAL        0xFF008080
#define COLOR_NAVY        0xFF000080
#define COLOR_LIME        0xFF00FF00
#define COLOR_OLIVE       0xFF808000
#define COLOR_MAROON      0xFF800000

// Dark Variants
#define COLOR_DARK_RED        0xFF800000
#define COLOR_DARK_GREEN      0xFF006400
#define COLOR_DARK_BLUE       0xFF00008B
#define COLOR_DARK_YELLOW     0xFF9B870C
#define COLOR_DARK_CYAN       0xFF008B8B
#define COLOR_DARK_MAGENTA    0xFF8B008B
#define COLOR_DARK_ORANGE     0xFFFF8C00
#define COLOR_DARK_PINK       0xFFCC3366
#define COLOR_DARK_PURPLE     0xFF4B0082
#define COLOR_DARK_BROWN      0xFF5C4033
#define COLOR_DARK_LIGHT_BLUE 0xFF6495ED
#define COLOR_DARK_LIGHT_GREEN 0xFF32CD32

// Light Variants
#define COLOR_LIGHT_RED       0xFFFF6666
#define COLOR_LIGHT_GREEN     0xFF66FF66
#define COLOR_LIGHT_BLUE      0xFF6666FF
#define COLOR_LIGHT_YELLOW    0xFFFFFF99
#define COLOR_LIGHT_CYAN      0xFF99FFFF
#define COLOR_LIGHT_MAGENTA   0xFFFF99FF
#define COLOR_LIGHT_ORANGE    0xFFFFB266
#define COLOR_LIGHT_PINK      0xFFFFB6C1
#define COLOR_LIGHT_PURPLE    0xFFB19CD9
#define COLOR_LIGHT_BROWN     0xFFCD853F
#define COLOR_LIGHT_GOLD      0xFFFFE066
#define COLOR_LIGHT_SILVER    0xFFE6E6FA

// Neon / Bright Colors
#define COLOR_NEON_GREEN      0xFF39FF14
#define COLOR_NEON_PINK       0xFFFF6EC7
#define COLOR_NEON_BLUE       0xFF1B03A3
#define COLOR_NEON_ORANGE     0xFFFF5F1F
#define COLOR_NEON_YELLOW     0xFFFFFD37
#define COLOR_NEON_CYAN       0xFF00FFF7
#define COLOR_NEON_PURPLE     0xFFBC13FE

// Pastel Colors
#define COLOR_PASTEL_RED      0xFFFF6961
#define COLOR_PASTEL_ORANGE   0xFFFFB347
#define COLOR_PASTEL_YELLOW   0xFFFFF68F
#define COLOR_PASTEL_GREEN    0xFF77DD77
#define COLOR_PASTEL_BLUE     0xFFAEC6CF
#define COLOR_PASTEL_PURPLE   0xFFCBAACB
#define COLOR_PASTEL_PINK     0xFFFFC0CB

// More web colors
#define COLOR_ALICE_BLUE      0xFFF0F8FF
#define COLOR_ANTIQUE_WHITE   0xFFFAEBD7
#define COLOR_AQUAMARINE      0xFF7FFFD4
#define COLOR_AZURE           0xFFF0FFFF
#define COLOR_BEIGE           0xFFF5F5DC
#define COLOR_BISQUE          0xFFFFE4C4
#define COLOR_BLANCHED_ALMOND 0xFFFFEBCD
#define COLOR_CORAL           0xFFFF7F50
#define COLOR_CORNFLOWER_BLUE 0xFF6495ED
#define COLOR_CRIMSON         0xFFDC143C
#define COLOR_DARK_KHAKI      0xFFBDB76B
#define COLOR_FIREBRICK       0xFFB22222
#define COLOR_FLORAL_WHITE    0xFFFFFAF0
#define COLOR_FOREST_GREEN    0xFF228B22
#define COLOR_GAINSBORO       0xFFDCDCDC
#define COLOR_HONEYDEW        0xFFF0FFF0
#define COLOR_HOTPINK         0xFFFF69B4
#define COLOR_INDIGO          0xFF4B0082
#define COLOR_KHAKI           0xFFF0E68C
#define COLOR_LAVENDER        0xFFE6E6FA
#define COLOR_LAVENDER_BLUSH  0xFFFFF0F5
#define COLOR_LAWN_GREEN      0xFF7CFC00
#define COLOR_LEMON_CHIFFON   0xFFFFFACD
#define COLOR_LIGHT_CORAL     0xFFF08080
#define COLOR_LIGHT_CYAN      0xFFE0FFFF
#define COLOR_LIGHT_GOLDENROD 0xFFFAFAD2
#define COLOR_LIGHT_PINK      0xFFFFB6C1
#define COLOR_LIGHT_SALMON    0xFFFFA07A
#define COLOR_LIGHT_SEA_GREEN 0xFF20B2AA
#define COLOR_LIGHT_SKY_BLUE  0xFF87CEFA
#define COLOR_LIGHT_SLATE_GRAY 0xFF778899
#define COLOR_LIGHT_STEEL_BLUE 0xFFB0C4DE
#define COLOR_LIGHT_YELLOW    0xFFFFFFE0
#define COLOR_LIME_GREEN      0xFF32CD32
#define COLOR_MEDIUM_AQUAMARINE 0xFF66CDAA
#define COLOR_MEDIUM_BLUE     0xFF0000CD
#define COLOR_MEDIUM_ORCHID   0xFFBA55D3
#define COLOR_MEDIUM_PURPLE   0xFF9370DB
#define COLOR_MEDIUM_SEA_GREEN 0xFF3CB371
#define COLOR_MEDIUM_SLATE_BLUE 0xFF7B68EE
#define COLOR_MEDIUM_SPRING_GREEN 0xFF00FA9A
#define COLOR_MEDIUM_TURQUOISE 0xFF48D1CC
#define COLOR_MEDIUM_VIOLET_RED 0xFFC71585


#endif // COLORS_H
